# `conda env update --file environment.yml --prune`
name: HF_SAT
channels:
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - python=3.11
  - pip
  - pytorch=2.2.1
  - pytorch-cuda=12.1
  - wandb=0.16.3
  - scikit-learn=1.4.1
  - matplotlib=3.8.0
  - pip:
    - transformers[torch]===4.38.1